### PR TITLE
fix: toggle theme button , hide scrollbar

### PR DESCRIPTION
**Pull request by sandeshkolte**

### CODE REVIEW

**Comment by sandeshkolte** [comment]
The toggle button now works fine, also added smooth transition on button hover in header, and hide the scroll bar.

**Review by sandeshkolte — COMMENTED** [review]
The changes are correct and should be merged

**Comment by allanoguis** [comment]
Hi @sandeshkolte I checked the PR and it looks like I got errors:

image
image

Although it did hide the scrollbar which is a good thing
Please check

**Comment by sandeshkolte** [comment]
I will check and solve it asap

**Pull request closed without merging**
