### PR TITLE
made the changes in the collaborations and made all the collaborators…

### PR DESCRIPTION
**Pull request by vaibhav-gosavi**
… dynamic in nature

image

made the ui look good and all the collaborators dynamic in nature

### CODE REVIEW

**Comment by vaibhav-gosavi** [comment]
hey the build is successfully just resolve the merge conflits

**Comment by vaibhav-gosavi** [comment]
this PR resolves #28

**Comment by vaibhav-gosavi** [comment]
hey @allanoguis  look into this PR  and Mege it solves #28 this issues

**Comment by allanoguis** [comment]
looking good!

**Comment by allanoguis** [comment]
The previous pull request had the old files in it. Make sure to have the updated branch in reference to the main. Or make a new branch directly from the issues panel. I think at this point I'll make you a maintainer too. You have done so much to this project and I thank you for your effort.

**Comment by allanoguis** [comment]
@vaibhav-gosavi I added you as a maintainer of this project. Please check this pull request as a maintainer it seems that the merge button is disabled on my end. I'm not sure if we should manually apply the changes but the tailwind configuration should be intact for the dark mode and the whole theme to work.

image

I suggest updating the branch before the merge. It worked for me earlier.

**Comment by vaibhav-gosavi** [comment]
ok i will look through it and make sure i merge the proper code

**Comment by allanoguis** [comment]
here is what i see on my end: 

image

**Pull request merged**
