### PR TITLE
UPDATED README.md file

### PR DESCRIPTION
**Pull request by soham0028**
Hello @allanoguis 
I have made all the necessary and promised changes to the file and leaving below ss of the changes for you to review :

kindly review :

image
----------------------------------------------------------------------------------------------------------
image
----------------------------------------------------------------------------------------------------------
image

### CODE REVIEW

**Comment by soham0028** [comment]
thankyou for the opportunity ,do review and make my work count under hacktoberfest

**Comment by soham0028** [comment]
it is showing me repo excluded

**Comment by soham0028** [comment]
why is this repo excluded???

**Comment by allanoguis** [comment]
Thanks @soham0028. Not sure why, I tried to contact the even organizers about this issue

**Pull request merged**
